pipeline {
  agent {
    docker { image 'node:latest' }
  }
  stages {
    stage('Install') {
      steps { sh 'npm install' }
    }

    stage('Test') {
      parallel {
        stage('Static code analysis') {
            steps { sh 'npm run lint' }
        }
        stage('e2e tests') {
            steps { sh 'npm run e2e' }
        }
      }
    }

    stage('Build') {
      steps { sh 'npm run build' }
    }
  }
}
