pipeline {

  agent {
    docker { image 'node:latest' }
  }


  stages {

   dir('Poker-Frontend'){
      sh 'pwd'
    }


    stage('Install') {
      steps { sh 'npm install' }
    }

      stage('e2e tests') {
            steps { sh 'ng e2e' }
        }


    stage('Build') {
      steps { sh 'ng build' }
    }
  }
}
